### ISSUE TITLE
https://afnemers.ruimtelijkeplannen.nl/ uit de lucht ...

### ISSUE THREAD

**Issue by oosterhagen** [opengeogroep/ruimtelijkeplannen#17]
https://afnemers.ruimtelijkeplannen.nl/ 404 ...

2023-11-08T16:57:56     WARNING    Traceback (most recent call last):
              File "C:\Users/Michiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 540, in addRPplanFromToolbar
              self.addFromIdn(self.toolbarSearch.text())
              File "C:\Users/Michiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 548, in addFromIdn
              (response, content) = self.nam.request(url, headers = self.rp_search_headers)
              File "C:\Users/Michiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\network\networkaccessmanager.py", line 267, in request
              raise self.http_call_result.exception
             RuimtelijkePlannen.network.networkaccessmanager.RequestsException: Network error #404: Error transferring https://afnemers.ruimtelijkeplannen.nl/plannenservice/plannen/identificatie/NL.IMRO.0079.BpBg10-Vg02 - server replied: Not Found

**Comment by MarcoDuiker** [comment]
De viewer van ruimtelijke plannen.nl doet het ook niet goed. 

Het lijkt erop of het onderhoud op 8 november is uiteglopen. Niet iets waar wij als plugin makers iets kunnen doen.
Het is zinvoller dit te melden op geoforum.nl

**Comment by MarcoDuiker** [comment]
De boel is weer gefixed.
